name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # or master, depending on your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout HayBox Config
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Checkout Pages Repository
        uses: actions/checkout@v3
        with:
          repository: rana-sylvatica/rana-sylvatica.github.io  # Replace with your username
          token: ${{ secrets.DEPLOY_TOKEN }}  # You'll need to create this
          path: pages-repo

      - name: Copy Build Files
        run: |
          rm -rf pages-repo/haybox-config
          mkdir -p pages-repo/haybox-config
          cp -r dist/* pages-repo/haybox-config/

      - name: Commit and Push
        run: |
          cd pages-repo
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "Update HayBox Config"
          git push